# Generated by Django 3.2.9 on 2021-11-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2013-09-12'),
            preserve_default=False,
        ),
    ]
